version: "2"
run:
  build-tags:
    - e2e
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - errorlint
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
formatters:
  enable:
    - gofmt
    - goimports
